base_url = "https://hibikilogy.github.io"
title = "äº¬å¹å­¦æŠ¥"
description = "å¹å­¦è‘—ä½œé›†é”¦"
default_language = "en"
output_dir = "build"
compile_sass = true
minify_html = false
ignored_content = ["temp.*"]
# generate_feed = true
# feed_filename = "rss.xml"
hard_link_static = false
taxonomies = [
  { name = "categories", feed = true, paginate_by = 10 },
  { name = "tags", feed = true, paginate_by = 10 },
  { name = "author", feed = true, paginate_by = 10 }
]
build_search_index = true

[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true
# A list of directories used to search for additional `.sublime-syntax` files.
extra_syntaxes = []
# The theme to use for code highlighting.
highlight_theme = "one-dark"
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => ğŸ˜„)
render_emoji = true
# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true
# Whether to set rel="nofollow" for all external links
external_links_no_follow = true
# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true
# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `â€¦`, `"quote"` into `â€œcurlyâ€` etc
smart_punctuation = false

# Configuration of the link checker.
[link_checker]
# Skip link checking for external URLs that start with these prefixes
skip_prefixes = ["http://[2001:db8::]/"]
# Skip anchor checking for external URLs that start with these prefixes
skip_anchor_prefixes = ["https://caniuse.com/"]

[slugify]
anchors = "on"
paths = "on"
taxonomies = "on"

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the path of the page/section in the index
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[translations]

[languages.zh]
author_text = "ä½œè€…"
publish_text = "å‘å¸ƒäº"
date_fromat = ""

[extra]
chart.enabled = true
footer = [
  { code = "en", tags_text = "æ ‡ç­¾", copyright = "æœ¬ç«™æ”¶å½•æ–‡ç« è‘—ä½œæƒå½’åŸä½œè€…æ‰€æœ‰", count = "æ€»æŸ¥è¯¢æ•°", frendlinks_text = "å‹æƒ…é“¾æ¥", list = [
    { text = "äº¬å¹å­¦æŠ¥", link = "$BASE_URL/" },
    { text = "RSS", link = "$BASE_URL/" },
    { text = "å¦‚ä½•è´¡çŒ®", link = "$BASE_URL/" },
    { text = "GitHub", link = "$BASE_URL/" },
  ], frendlinks = [
    { text = "ä¸­å›½ç‚å­¦é™¢ç»´åŸº", link = "$BASE_URL/" },
    { text = "ç²³ç±³å›¢å­", link = "$BASE_URL/" },
  ], contact = { text = "æŠ•ç¨¿é‚®ç®± journal@kyoani.cn", link = "journal@kyoani.cn" } },
]
section = [{ code = "en", publish = "å‘è¡¨äº", author = "ä½œè€…" }]
galleria.enabled = true
katex.auto_render = true
katex.enabled = true
mermaid.enabled = true
navbar = [
  { code = "en", list = [
    { text = "æˆ‘è¦æŠ•ç¨¿", link = "$BASE_URL/" },
    { text = "èƒ½åŠ›é‰´å®š", link = "$BASE_URL/" },
    { text = "å®ä½“ç‰ˆç‰¹åˆŠ", link = "$BASE_URL/" },
  ] },
]
social_link = [{ code = "en", text = "å¹å­¦è‘—ä½œé›†é”¦", link = '/' }]

[extra.favicon]
apple_touch_icon = "/icons/apple-touch-icon.png"
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

[extra.analytics]
google = ""

[features]
default = ["rust-tls"]
indexing-zh = ["libs/indexing-zh"]
native-tls = ["libs/native-tls"]
rust-tls = ["libs/rust-tls"]
